### ISSUE TITLE
Fields not sent

### ISSUE THREAD

**Issue by Poliondas** [inicialsolucoes/itaucripto-php#1]
The field setBankSlipNoteLine[1-3] is not being sent.

The bank generates the slip without the info.

**Comment by fabianocouto** [comment]
Hi, @Poliondas ! To display the lines on the bank slip, you must set note as 3, something like this: 

`$itaucripto->setBankSlipNoteLine1('Line 1');`
`$itaucripto->setBankSlipNoteLine2('Line 2');`
`$itaucripto->setBankSlipNoteLine3('Line 3');`
`$itaucripto->setNote('3');`

**Comment by Poliondas** [comment]
Thanks.
It works perfectly after add this line.
