### ISSUE TITLE
Exibição de "APOS O VENCIMENTO COBRAR MORA DE R$ ............... 0,20 AO DIA"

### ISSUE THREAD

**Issue by felipegallo** [inicialsolucoes/itaucripto-php#2]
Ola,

Utilizo a biblioteca e ela é excelente! Porém, em todas as implementações a seguinte mensagem é sempre exibida nos boletos gerados:

"APOS O VENCIMENTO COBRAR MORA DE R$ ............... 0,20 AO DIA"

Sempre antes das notas que normalmente seto pelos setters de "BankSlipNoteLine". Alguém saberia onde/como fazer para que isso não seja exibido?

**Comment by fabianocouto** [comment]
Oi, @felipegallo! Eu acredito que essa mensagem venha do próprio sistema do Itaú. No painel da empresa, no sistema do banco, também possível cadastrar informações adicionais do boleto, e provavelmente é de lá que está vindo essa informação. Desculpe a demora na resposta.
